name: jax-sac
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.2
  - scipy=1.6.0
  - pip:
    - absl-py==0.11.0
    - gym==0.18.0
    - tqdm==4.50.2
    - flax==0.3.0
    - jax==0.2.9
    - jaxlib==0.1.59
    - tensorflow_probability==0.12.1
prefix: $HOME/anaconda3
